server:
  port: 8111
#  servlet:
#    context-path: /hi
ibm:
  mq:
    servers:
      - queueManager: QM1
        channel: DEV.ADMIN.SVRCONN
        connName: localhost(1414)
        user: ${user:admin}
        password: ${password:passw0rd}
    queues:
      - DEV.QUEUE.1
      - DEV.QUEUE.2
    queue: >
      DEV.QUEUE.1
#      DEV.QUEUE.2
    message_folder: ${msg_folder:folder}
message_folder: ${msg_folder:folder}
test:
  lavel: >
    tst,
    tst2


