server:
  port: 8111
#  servlet:
#    context-path: /hi
ibm:
  mq:
    servers:
      - queueManager: QM1
        channel: DEV.ADMIN.SVRCONN
        connName: localhost(1414)
        user: admin
        password: passw0rd

